version: "3"

services:
  kms:
    container_name: local-kms-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/nsmithuk/local-kms
      - ./init:/init
      - ./data:/data
    ports:
      - 8080:8080
